myproject/core/urls.py
from django.urls import path

from myproject.core import views as v

app_name = 'core'

urlpatterns = [
    path('', v.index, name='index'),
    path('persons/serverside/', v.persons_serverside, name='persons_serverside'),  # noqa E501
    path('person/json/', v.person_json, name='person_json'),
]

myproject/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('myproject.core.urls')),
    path('admin/', admin.site.urls),
]

myproject/core/models.py
from django.db import models

STATUS = (
    ('0', ''),
    ('p', 'pendente'),
    ('c', 'cancelado'),
    ('a', 'aprovado'),
)


class Person(models.Model):
    name = models.CharField('nome', max_length=100)
    email = models.EmailField(null=True, blank=True)
    phone = models.CharField('telefone', max_length=11, null=True, blank=True)
    status = models.CharField(
        max_length=1,
        choices=STATUS,
        default='p'
    )

    class Meta:
        ordering = ('name',)
        verbose_name = 'Pessoa'
        verbose_name_plural = 'Pessoas'

    def __str__(self):
        return self.name

    def to_dict_json(self):
        return {
            'pk': self.pk,
            'name': self.name,
            'email': self.email,
            'phone': self.phone,
            'status': self.get_status_display(),
        }

myproject/core/views.py
import math

from django.db.models import Q
from django.http import JsonResponse
from django.shortcuts import render

from .models import Person


def index(request):
    person_list = Person.objects.all()
    context = {'person_list': person_list}
    return render(request, 'index.html', context)


def person_json(request):
    persons = Person.objects.all()
    total = persons.count()

    search = request.GET.get('search[value]')

    if search:
        persons = persons.filter(
            Q(name__icontains=search) |
            Q(email__icontains=search) |
            Q(phone__icontains=search)
        )

    _start = request.GET.get('start')
    _length = request.GET.get('length')
    if _start and _length:
        start = int(_start)
        length = int(_length)
        page = math.ceil(start / length) + 1  # [opcional]
        per_page = length  # [opcional]

        persons = persons[start:start + length]

    data = [person.to_dict_json() for person in persons]
    response = {
        'data': data,
        'recordsTotal': total,
        'recordsFiltered': total,
    }
    return JsonResponse(response)


def persons_serverside(request):
    template_name = 'persons_serverside.html'
    return render(request, template_name)

myproject/core/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">
  <link rel="icon" href="https://getbootstrap.com/favicon.ico">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.css">
  <link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap4.min.css">

  <!-- Font-awesome -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">


  <title>DataTables example</title>

  <style>
    body {
      padding-top: 3.5rem;
    }
  </style>
</head>
<body>

    {% include "nav.html" %}

    <main role="main">

    {% block content %}{% endblock content %}

    </main>

    <footer class="container">
      <p>&copy; Company 2018</p>
    </footer>

  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.3.1.js"></script>
  <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
  <script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap4.min.js"></script>

  {% block js %}{% endblock js %}
</body>
</html>

myproject/core/templates/index.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<!-- Main jumbotron for a primary marketing message or call to action -->
<div class="jumbotron">
  <div class="container">
    <h2>Exemplo do uso de <a href="https://datatables.net/" target="_blank">DataTables</a></h2>
    <p>Exemplo do uso de DataTables com Django.</p>
    <!-- <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more &raquo;</a></p> -->
  </div>
</div>

<div class="container">
  <!-- Example row of columns -->
  <div class="row">
    <div class="col-md-6">
      <h2>Contatos</h2>
      <table id="myTable1" class="table">
        <thead>
          <tr>
            <th>Nome</th>
            <th>E-mail</th>
            <th>Telefone</th>
            <th>Status</th>
          </tr>
        </thead>
        <tbody>
          {% for person in person_list %}
            <tr>
              <td>{{ person.name }}</td>
              <td>{{ person.email }}</td>
              <td>{{ person.phone }}</td>
              <td>{{ person.get_status_display }}</td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
    <div class="col-md-6">
      <h2>Contatos via JSON</h2>
      <table id="myTable2" class="table">
        <thead>
          <tr>
            <th>Nome</th>
            <th>E-mail</th>
            <th>Telefone</th>
            <th>Status</th>
          </tr>
        </thead>
      </table>
    </div>
  </div>

  <hr>

</div> <!-- /container -->

{% endblock content %}

{% block js %}

<script src="{% static 'js/data.js' %}"></script>

{% endblock js %}

myproject/core/templates/nav.html
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
  <a class="navbar-brand" href="#">Exemplo</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'core:index' %}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'core:persons_serverside' %}">DataTable ServerSide</a>
      </li>
      <!-- <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="http://example.com" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Dropdown</a>
        <div class="dropdown-menu" aria-labelledby="dropdown01">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li> -->
    </ul>
  </div>
</nav>

myproject/core/templates/persons_serverside.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<div class="jumbotron">
  <div class="container">
    <h2>Exemplo do uso de <a href="https://datatables.net/" target="_blank">DataTables</a></h2>
    <p>Exemplo do uso de DataTables em <a href="https://datatables.net/examples/data_sources/server_side.html" target="_blank">Server-side render processing</a> com Django.</p>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="cols">
      <h2>DataTables Server-side render </h2>
      <table id="myTable" class="table">
        <thead>
          <tr>
            <th>Nome</th>
            <th>E-mail</th>
            <th>Telefone</th>
            <th>Gênero</th>
          </tr>
        </thead>
      </table>
    </div>
  </div>

  <hr>

</div> <!-- /container -->

{% endblock content %}

{% block js %}

<script>
  $(document).ready( function () {
    $('#myTable').DataTable({
      "processing": true,
      "serverSide": true,
      "ajax": "/person/json/",
      "columns": [
        {"data": "name"},
        {"data": "email"},
        {"data": "phone"},
        {"data": "status"}
      ]
    });
  });

</script>

{% endblock js %}